services:
  db:
    image: postgres:latest
    container_name: postgres_wb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    ports:
      - 5433:5432

    volumes:
      - ./data:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
        - wb-tariffs

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3333:3333
    env_file:
        - ./.env

    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src/
          ignore: 
            - node_modules
        - action: rebuild
          path: package.json

    networks:
        - wb-tariffs
    command: ["npm", "run", "start"]
  
volumes:
  data:

networks:
  wb-tariffs:
    driver: bridge
