services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - 5433:5433

    volumes:
      - ./data:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
        - wb-tariffs

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3333:3333
    env_file:
        - ./.env

    depends_on:
      db:
        condition: service_healthy

    networks:
        - wb-tariffs
    command: ["npm", "run", "start"]
  
volumes:
  data:

networks:
  wb-tariffs:
    driver: bridge
